spring:
  application:
    name: service-zuul

server:
  port: 5000

# Eureka \u5BA2\u6237\u7AEF\u914D\u7F6E
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka #eureka

zuul:
  routes:
    feignApi:
      path: /feignapi/**
      serviceId: eureka-feign-client
    hiApi:
      path: /hiapi/**
      serviceId: eureka-client