FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /user/docker_dir/eureka_server_tmp
ADD eureka-server-0.0.1-SNAPSHOT.jar
#RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","eureka-server-0.0.1-SNAPSHOT.jar"]
EXPOSE 8761