spring:
  application:
    name:
      eureka-fegin-client
server:
  port: 0

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka #eureka\u670D\u52A1\u6CE8\u518C\u5730\u5740

# 断路器hystrix - feign已经引入了hystrix的起步依赖，只需开启即可
feign:
  hystrix:
    enabled: true
